---
version: "3.8"
services:
  redis-server: 
    image: "redis"
  node-app: 
    build: .
    expose:
      - "8081"  
  nginx:
    image:
      nginx:latest
    volumes:
      - ./nginx.cfg:/etc/nginx/nginx.conf:ro
    depends_on:
      - node-app
    ports:
      - "4000:4000"